### PR TITLE
2.2.9: Update size and hash

### PR DESCRIPTION
**Pull request by A6GibKm**
It seems they changed the deb without changing its filename.

### CODE REVIEW

**Comment by A6GibKm** [comment]
Tested and it launchs just fine.

**Comment by gasinvein** [comment]
Wait, what? Did they just revert previous update? Checksum in 78609432b52fc272449200f55dc46d0df6604c0e was from the value now set in this PR.

**Comment by A6GibKm** [comment]
yeah, it was reverted, I don't know why.

**Comment by Garbee** [comment]
The bot handles this stuff for most cases. Please be patient for that to do its job and only if it seems broken do a PR to update it or flag the PR/an issue about the bot being broken.

Generally, the bot works fine. Only in odd cases does Jagex break it. And now the automerge thing for the bot is fixed too.

**Comment by A6GibKm** [comment]
Well this PR was sent specifically because the flatpak would fail to launch due to a wrong hash submitted by the bot. This situation lasted for almost a month.

See https://github.com/flathub/com.jagex.RuneScape/commit/d43b2f00661df9cb3e90d126b53e8b49e4f126d3

**Comment by gasinvein** [comment]
The hash wasn't wrong. As I understand, the following happened: the upstream pushed an update (applied in 78609432b52fc272449200f55dc46d0df6604c0e), then decided to revert it and pushed the previous version (applied d43b2f00661df9cb3e90d126b53e8b49e4f126d3), and then pushed the update again. But since the update was already commited in 78609432b52fc272449200f55dc46d0df6604c0e, the bot didn't submit the same update anymore.

**Comment by Garbee** [comment]
Ah, so Jagex broke out by rolling back and the bot thought it was already gone by. Hmm. Not sure if the bot by flathub should do anything about that. I can probably setup a custom one though to handle it.

**Comment by gasinvein** [comment]
I wonder how a debian repo maintained like this works for normal users. What does APT do in cases like this (changing a package back and forth without version/release change)?

**Comment by Garbee** [comment]
As far as I am aware, it just pulls whatever is sitting there. Jagex runs their own repo. No external vendors redistribute it. So Jagex can basically do whatever they want and the lady sitting version is what is latest.

**Pull request closed without merging**
