### PR TITLE
Update debian data

### PR DESCRIPTION
**Pull request by Garbee**
Automatic update of debian metadata

### CODE REVIEW

**Comment by Tjzabel** [comment]
This fixed my installation issues :+1:

**Comment by Garbee** [comment]
@Tjzabel Yea I know they will. These PRs are automatically made, I just haven't figured out how to auto-merge them due to bad API docs from the Octokit team.

**Comment by Tjzabel** [comment]
@Garbee it may be worth adding a [merge PR](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button) hook into the script that makes this PR.

**Comment by Garbee** [comment]
The problem is I am not using their HTTP client directly. I am using Octokit (the now official JS client to it) which is just plain wrong in what it documents. They say `pullNumber` is required and `number` is optional. In reality, *BOTH* are required. So I did a bunch of testing with one vs the other because of the docs, but never tested with both properties on the sent object. Well, now I know.

It should be working now for auto-merging in the future. We won't know for certain until the next update happens.

**Comment by Tjzabel** [comment]
Hmm, okay. I was looking at the [go-github](https://github.com/google/go-github) library, which is pretty well documented.

If the auto-merging works next week, it may be worthwhile sending a PR to fix those docs so others don't fall for the same issue.

**Comment by Garbee** [comment]
> may be worthwhile sending a PR to fix those docs

IMO the docs aren't wrong. It's the code internally that is the problem. There is no reason the PR number should need to be duplicated. That is something Github needs to figure out with Octokit to just get the code sane (or perhaps they have and the version I require is just outdated.)

There is far more nuance to doc problems then than simply, "If the docs don't work correct the docs". It has to be understood where the true error lies and how to address it properly. While I could dig into Octokit and figure out the problem there, I just don't have the time with all my day job stuff.

**Comment by Tjzabel** [comment]
Ah. I figured it was only a docs error.

In that case,  yeah it would probably take some time to dig through the library :sweat_smile:

**Pull request merged**
