### PR TITLE
Update client to 2.2.5.

### PR DESCRIPTION
**Pull request by allan4229**
The client had to be updated since the current version being used by the project (2.2.4) leads to 404 as of the linux client update from 2019-11-11.
Since I found this project to be the alternative when my old configuration stopped working because of this update, I wanted to save you a little bit of time with this update as a thanks.

### CODE REVIEW

**Comment by Garbee** [comment]
This was already covered in PR #97. I have an automated script that looks for updates and makes a PR. It just needs to be manually merged.

Thank you for at least attempting to correct this in your own though.

**Comment by Garbee** [comment]
Sorry, I’m on mobile (at a development conference away from a pc.) didn’t see that the launcher number was updated in the changes. I’ll have to take a look at all this when I’m back at a system I can run builds on. If they’re claiming they made launcher improvements then I may have more work to do due to other workarounds I put in if they fixed those bugs.

**Comment by allan4229** [comment]
I don't know what strategy you're using for the automation, but if for any chance you're running a container you could :
`apt-get install --print-uris --reinstall runescape-launcher | perl -lne "/'(.*?)'/;print \$1" | tail -1`
To get the .deb URI.
But if the script tries the URI directly then things get more difficult due to the repo not listing its contents.

**Comment by marcthe12** [comment]
@Garbee Testing it, seems to run. No issues till now on 18.08.
Xdotool can be dropped safely.
All non runtime deps aside from gtk2 can be safely droped.
The audio workaround can be dropped if we can get the capabilities to work in the sandbox (Did not work with snap). This a quote regarding this:

> Also of note is the new postinst script that grants CAP_SETFCAP on the launcher binary - this is sed ONLY to grant the permission to adjust thread priorities to the client binary, which allows the audio threads to be high priority, fixing a long-standing linux audio issue. If there is a nicer way you can come up with to grant CAP_SYS_NICE to the client binary then please do so instead.

There is an issue mention by @AsciiWolf in #94  where openssl does not work in 19.08 runtime although that works in 18.08. Can be looked independently.

**Comment by Garbee** [comment]
There is a reason I have not automated that URL and probably never will. I have workarounds to their bugs. I looked at the patch notes, sure enough they fixed most of the workarounds I put into place to make the experience better.

Fixing this to install and run properly isn't as easy as just updating the URL and calling it done. I need to go remove the workarounds and test to verify the new launcher works properly within a container.

Since there is going to be quite a bit of work to get this fixed, I'm closing this out. There is an issue already about the install failing, I'll link the fix pr to that so watch it for updates.

**Comment by marcthe12** [comment]
@Garbee just a simple question, I have a tested some changes and figured thing did to fixes do you mind I create a new pr with all the changes (Only audio work around is untested but current fix is good enough for now.

**Pull request closed without merging**
