### PR TITLE
Fix crackling audio

### LINKED ISSUE #6: Fedora 27 audio issues
I'm experiencing very broken audio on up to date fedora 27, I'm running 64 bit, with latest updates and I noticed that music was muted the first time I launched runescape, and I noticed shortly after that this might have been because sound is heavily broken. The game runs fine on Windows, yet it runs graphically quite well here with Fedora but struggles in the audio.

I'm running fedora on amd processor and an amd graphics card, if that helps.

### PR DESCRIPTION
**Pull request by AsciiWolf**
Fixes #6.

### CODE REVIEW

**Comment by Garbee** [comment]
This solution isn't quite as versatile as I'd like. We should have the script first do the same env check as Arch (for consistency) and only export if not defined. That way a user can run the flatpak with the `--env` option to set this if they happen to need a different latency setting.

Ideally we'd look [just like arch](https://aur.archlinux.org/cgit/aur.git/commit/?h=runescape-launcher&id=7c1b5b9995ef21ddb5a88fa3061cc50cb967490e) for this setting. But with 120ms instead of 60 as our default since there is probably some inherit extra latency going on between the flatpak runtime and the OS.

Would you like to update the PR to reflect this?

**Comment by AsciiWolf** [comment]
@Garbee I have tried this, but it didn't work:
```
                {
                    "type": "script",
                    "commands": [
                        "[ '$PULSE_LATENCY_MSEC' ] || export PULSE_LATENCY_MSEC='120'",
                        "/app/extra/runescape-launcher $@"
                    ],
                    "dest-filename": "runescape.sh"
                },
```

**Comment by Garbee** [comment]
The only issue with your original test of the way Arch does it, is you didn't put `exec` on the launcher execution line. I have it working perfectly with that.

However what this causes is... the crackling on my machine. 60ms and 120ms both crackle. 30ms kills audio completely. Only 80 and 100ms increments provide clean sound.

So I'd like to see us use the Arch method. Your original patch works perfect, just add `exec ` at the start of the line to run the launcher. But, we should have the default ms set to 80. Since that's the lowest increment that provides no distortion on Ubuntu systems (what the original debian is built for) and if users need to edit that then they can run it like so:

`flatpak run --env=PULSE_LATENCY_MSEC=120 com.jagex.RuneScape`

**Comment by AsciiWolf** [comment]
80ms works for me as well. I have updated the PR, feel free to merge it. :-)

**Comment by Garbee** [comment]
Sweet, thank you!

I'll be updating the repo later today to make maintaining these scripts easier. Just learned how we can use actual files instead of cramming it into JSON. :smile:

**Pull request merged**
