### PR TITLE
Update sdk to version 19.08

### PR DESCRIPTION
**Pull request by marcthe12**
solves #89

### CODE REVIEW

**Comment by Garbee** [comment]
I need to get a VM setup to test this change. The remote build is failing which is not a good sign. That indicates to me that this change is going to need some more work than just updating the reference. Which is exactly why I haven't done this yet. But, I should still test locally just in case it is an intermittent remote build system failure.

**Comment by marcthe12** [comment]
@Garbee Just try one more time, I had forgot to update the shared modules. So it could be just a human error.

**Comment by marcthe12** [comment]
I seems

**Comment by marcthe12** [comment]
sucess

**Comment by marcthe12** [comment]
Okay I am testing it on my pc. Seems to running ok.

**Comment by Garbee** [comment]
So I just tried to get a newer build on this going in a VM, it kept failing to start (probably due to this being a GPU heavy game in a VM already with what is a weak GPU itself.) So, this sadly needs to wait until after Chrome Dev Summit this week to get verified when I can have the time to setup a physical machine to test on. Or just dual-boot my laptop to have Linux on it.

It is not lost in the aether, just needs 2 or 3 hours of focused work to get a physical machine figured out which I don't have before my flight early tomorrow.

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
I have tried this PR in combination with #98, unfortunately the launcher did not run:
`/app/extra/runescape: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

I have tried to workaround it:
```
diff --git a/com.jagex.RuneScape.json b/com.jagex.RuneScape.json
index 60db054..3678e40 100644
--- a/com.jagex.RuneScape.json
+++ b/com.jagex.RuneScape.json
@@ -121,7 +121,9 @@
                 "install runescape.sh /app/bin/runescape",
                 "install -Dm644 com.jagex.RuneScape.appdata.xml /app/share/appdata/com.jagex.RuneScape.appdata.xml",
                 "cp /usr/bin/ar /app/bin",
-                "ARCH_TRIPLE=$(gcc --print-multiarch) && cp /usr/lib/${ARCH_TRIPLE}/libbfd-*.so /app/lib"
+                "ARCH_TRIPLE=$(gcc --print-multiarch) && cp /usr/lib/${ARCH_TRIPLE}/libbfd-*.so /app/lib",
+                "ARCH_TRIPLE=$(gcc --print-multiarch) && ln -s /usr/lib/${ARCH_TRIPLE}/libcrypto.so.1.1 /app/lib/libcrypto.so.1.0.0",
+                "ARCH_TRIPLE=$(gcc --print-multiarch) && ln -s /usr/lib/${ARCH_TRIPLE}/libssl.so.1.1 /app/lib/libssl.so.1.0.0"
             ],
             "sources": [
                 {
diff --git a/scripts/runescape.sh b/scripts/runescape.sh
index b18040a..05f259d 100644
--- a/scripts/runescape.sh
+++ b/scripts/runescape.sh
@@ -4,6 +4,7 @@
 # This is to fix crackling audio issues when running inside of the container.
 [ '$PULSE_LATENCY_MSEC' ] || export PULSE_LATENCY_MSEC='80'
 
+export LD_LIBRARY_PATH=/app/lib
 exec /app/extra/runescape-launcher "$@" &
 
 if [ -z "${SHOW_LAUNCHER}" ]; then
```

Unfortunately, it did not help:
```
/app/extra/runescape: /app/lib/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /app/extra/runescape)
/app/extra/runescape: /app/lib/libssl.so.1.0.0: version `OPENSSL_1.0.1' not found (required by /app/extra/runescape)
/app/extra/runescape: /app/lib/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by /app/extra/runescape)
/app/extra/runescape: /app/lib/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /app/extra/runescape)
```

It needs manually built, older version of OpenSSL.

**Comment by marcthe12** [comment]
Jagex said this is a bug. There seems to be improper linking of the openssl library.

https://aur.archlinux.org/packages/runescape-launcher/#comment-715718

**Comment by marcthe12** [comment]
@AsciiWolf I think we priortize #98. I can look in to this after that PR merges

**Comment by Garbee** [comment]
#98 is merged now and I have a physical machine up to test things. So if anyone wants to look back over this stuff and rebase in the next week or two then it should be a relatively quick merge.

**Comment by marcthe12** [comment]
Why openssl has to have their configure script with ./Configure not ./configure.

We need to port this into our manifest as openssl in 18.08 works but 19.08 they removed the required version:
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/freedesktop-sdk-18.08.37/elements/base/openssl-1.0.bst

Can't figure out so need advise.

Jagex is aware of this and said it will be fixed in next release.
Not sure when is soon

**Comment by Garbee** [comment]
Personally I don't mind waiting for Jagex on something like this. Unless there is some super-compelling reason to upgrade the SDK to 19.08 as soon as possible.

**Comment by marcthe12** [comment]
Not sure how long Jagex takes though.

**Comment by Garbee** [comment]
Does it matter how long they take unless we have a compelling reason to work around that problem?

What does upgrading the SDK actually do for operating the program?

**Comment by AsciiWolf** [comment]
Upgraded runtime brings, for example a new Mesa, and other updates that can improve performance.

**Comment by Garbee** [comment]
Unless we have some numbers to show the updated performance metrics are a noticeable improvement to end users of this package, I see no point to go through the pain.

**Comment by marcthe12** [comment]
Mergeable.

**Comment by eszlari** [comment]
> Unless we have some numbers to show the updated performance metrics are a noticeable improvement to end users of this package, I see no point to go through the pain.

It's mot only performance, but also support for newer hardware (GPUs).

**Comment by Garbee** [comment]
Seems to be running fine here. Thanks for looking into this and doing the work.

**Pull request merged**
